platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'


target 'AelfApp' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'Moya','~> 12.0' # 网络请求 https://github.com/Moya/Moya
  pod 'Kingfisher' # 图片下载 https://github.com/onevcat/Kingfisher
  pod 'SnapKit' # Layout 布局 https://github.com/SnapKit/SnapKit
  pod 'WCDB.swift' # 腾讯数据库 https://github.com/Tencent/wcdb
  pod 'IQKeyboardManagerSwift' # 键盘管理 https://github.com/hackiftekhar/IQKeyboardManager
  pod 'Bugly' # 崩溃统计 https://bugly.qq.com/v2/

  pod 'LTMorphingLabel' # 文字动画 https://github.com/lexrus/LTMorphingLabel
#  pod 'BouncyLayout' #collection 滑动弹性动画 https://github.com/roberthein/BouncyLayout
  
  pod 'Schedule' # 时间调度 https://github.com/luoxiu/Schedule
  pod 'ViewAnimator' # 动画库 https://github.com/marcosgriselli/ViewAnimator
  pod 'SwifterSwift' # 类似 YYKit https://github.com/SwifterSwift/SwifterSwift
  pod 'Localize-Swift' # 国际化 https://github.com/marmelroy/Localize-Swift
  pod 'Then' # 语法糖 https://github.com/devxoul/Then
  pod 'SwiftMessages' #  UI 弹框库 https://github.com/SwiftKickMobile/SwiftMessages
  pod 'DZNEmptyDataSet'  # 老版空态框架 https://github.com/dzenbot/DZNEmptyDataSet
  pod 'KafkaRefresh' # 刷新框架 https://github.com/OpenFeyn/KafkaRefresh

  pod 'SVProgressHUD' # HUD 弹框
  pod 'Hero'  # https://github.com/HeroTransitions/Hero
  pod 'MYTableViewIndex' # 地址薄索引
  pod 'MarqueeLabel' # 跑马灯 https://github.com/cbpowell/MarqueeLabel
  pod 'FSPagerView' # 轮播图 https://github.com/WenchaoD/FSPagerView
  pod 'JXSegmentedView' # Segment 分页 https://github.com/pujiaxin33/JXSegmentedView
  pod 'SwiftyAttributes' # 富文本字符串 https://github.com/eddiekaiger/SwiftyAttributes
  pod 'UITextView+Placeholder'
  pod 'CropViewController' # Crop Image https://github.com/TimOliver/TOCropViewController
  pod 'ESTabBarController-swift' # https://github.com/eggswift/ESTabBarController
  pod 'WKWebViewJavascriptBridge', '~> 1.2.0' # https://github.com/Lision/WKWebViewJavascriptBridge
  pod 'FoldingCell'  # 折叠 cell https://github.com/Ramotion/folding-cell

  pod 'Closures' # 事件回调 https://github.com/vhesener/Closures

  # Rx 相关
  pod 'RxSwift' # https://github.com/ReactiveX/RxSwift
  pod 'RxCocoa'
  pod 'RxDataSources'  # https://github.com/RxSwiftCommunity/RxDataSources
  pod 'Moya/RxSwift'
  pod 'NSObject+Rx' # https://github.com/RxSwiftCommunity/NSObject-Rx
  pod 'Moya-ObjectMapper','~> 2.8' # https://github.com/bmoliveira/Moya-ObjectMapper
  # pod 'Moya-ObjectMapper/RxSwift', :git => 'https://github.com/814349837/Moya-ObjectMapper', :commit => '6347b7bde5'

  # pod 'ObjectMapper', '~> 3.3'

  pod 'Validator' # 表单验证 https://github.com/adamwaite/Validator
  pod 'Result' # https://github.com/antitypical/Result

  pod 'Cache' # 缓存库

  # 区块链相关库
  pod 'BitcoinKit', '~> 1.1.0' # #// bitcoin need it : brew install autoconf automake libtool
  pod 'KeychainSwift' # https://github.com/evgenyneu/keychain-swift
  pod 'SwiftyRSA' # https://github.com/TakeScoop/SwiftyRSA

  # Umeng 推送
  pod 'UMCPush', '~> 3.2.4' # push
  pod 'UMCAnalytics' # 统计
  pod 'UMCCommon', '~> 2.0.1'
  
  pod 'JJException'  # Crash 拦截 https://github.com/jezzmemo/JJException
  
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['LD_NO_PIE'] = 'NO'
    end
  end
end
